name: Compile Examples

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Install Arduino CLI manually
      - name: Install Arduino CLI
        run: |
          wget -qO- https://downloads.arduino.cc/arduino-cli/arduino-cli_latest_Linux_64bit.tar.gz | tar -xvz
          sudo mv arduino-cli /usr/local/bin/
          arduino-cli version

      # Ensure that Bash is used for compatibility with the prebuild script
      - name: Ensure Bash Shell
        run: sudo ln -sf /bin/bash /bin/sh

      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Update the Arduino core index and install required platform
      - name: Install Arduino Core
        run: |
          arduino-cli core update-index
          arduino-cli core install Inkplate_Motion:stm32

      # Compile all examples and fail fast on error
      - name: Compile examples
        run: |
          set -e # Exit immediately if a command exits with a non-zero status
          for sketch in $(find examples -name '*.ino'); do
            echo "Compiling $sketch"
            arduino-cli compile --fqbn Inkplate_Motion:stm32:Inkplate6Motion "$sketch" --warnings=all --verbose
          done
