name: Compile Examples

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - board:
              fqbn: Inkplate_Motion:stm32:Inkplate6Motion
            additional-sketch-paths: |
              - examples

    steps:
      # Ensure that Bash is used for compatibility with the prebuild script
      - name: Ensure Bash Shell
        run: sudo ln -sf /bin/bash /bin/sh

      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Compile all examples
      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          platforms: |
            - source-url: https://github.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE/raw/master/package_Dasduino_Boards_index.json
              name: Inkplate_Motion:stm32

          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            - source-path: ./
          sketch-paths: |
            ${{ matrix.additional-sketch-paths }}
