name: Compile Examples

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Ensure that Bash is used for compatibility with the prebuild script
      - name: Ensure Bash Shell
        run: sudo ln -sf /bin/bash /bin/sh

      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Install necessary platforms
      - name: Install Arduino Core
        run: |
          arduino-cli core update-index
          arduino-cli core install Inkplate_Motion:stm32

      # Compile all examples and fail fast on error
      - name: Compile examples
        run: |
          set -e # Exit immediately if a command exits with a non-zero status
          for sketch in $(find examples -name '*.ino'); do
            echo "Compiling $sketch"
            arduino-cli compile --fqbn Inkplate_Motion:stm32:Inkplate6Motion "$sketch" --warnings=all --verbose
          done
